version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "currency-convertor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pgncbrx9exjr"
s3_prefix = "currency-convertor"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
